# netlify.toml
# This fixes the Next.js 15 / App Router 404 error on Netlify

[build]
  command = "npm run build"
  publish = ".next"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

[build.environment]
<<<<<<< HEAD
  NEXT_DISABLE_NETLIFY_PLUGIN = "true"
=======
  NEXT_DISABLE_NETLIFY_PLUGIN = "true"
>>>>>>> 6275fee53c8ea7d19d7251e1047bd7299d08d53b
